# Generated by Django 3.0.8 on 2020-07-16 17:35

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryClassifierModel',
            fields=[
                ('model_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('model', picklefield.fields.PickledObjectField(default=None, editable=False)),
                ('is_training', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('crte_ts', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
