# Generated by Django 3.0.8 on 2020-07-23 14:39

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryClassifierModel',
            fields=[
                ('model_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('model', picklefield.fields.PickledObjectField(default='', editable=False)),
                ('is_training', models.BooleanField(default=True)),
                ('crte_ts', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binary_classifier_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='training_data', to='binary_classifier_app.BinaryClassifierModel')),
                ('x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('label', models.BooleanField()),
                ('crte_ts', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
